from pydantic import BaseModel, Field

class DecisionResponse(BaseModel):
    symbol: str = Field(..., description="The stock ticker symbol (e.g. AAPL)")
    signal: str = Field(..., description="The generated action recommendation: BUY, SELL, or HOLD")
    confidence: float = Field(..., description="The consolidated prediction probability representing signal strength")
    close_price: float = Field(..., description="The latest closing price observed for the asset")
    explanation: str = Field(..., description="Natural language reasoning generated by the explainer layer")
    timestamp: str = Field(..., description="ISO 8601 timestamp representing when the decision was executed")
