import numpy as np
import pandas as pd
from typing import Dict, Any, Optional
from stonks.models.base_model import BaseModel
from stonks.logging.logger import logger
from stonks.config.settings import settings

class WeightedEnsemble:
    """Ensemble framework that aggregates predictions from multiple base models using weighted voting."""
    
    def __init__(self, initial_weights: Optional[Dict[str, float]] = None):
        self.models: Dict[str, BaseModel] = {}
        # Load default weights from settings if not explicitly provided
        self.weights: Dict[str, float] = initial_weights or settings.ensemble_weights
        
    def register_model(self, name: str, model_instance: BaseModel) -> None:
        """Registers an active model instance to the ensemble."""
        clean_name = name.strip().lower()
        self.models[clean_name] = model_instance
        # Initialize weight to 0.0 if not already configured in settings
        if clean_name not in self.weights:
            self.weights[clean_name] = 0.0
        logger.info(f"Registered model '{clean_name}' in WeightedEnsemble.")
        
    def remove_model(self, name: str) -> None:
        """Removes a model from the active ensemble."""
        clean_name = name.strip().lower()
        if clean_name in self.models:
            del self.models[clean_name]
        logger.info(f"Removed model '{clean_name}' from WeightedEnsemble.")
        
    def set_weight(self, name: str, weight: float) -> None:
        """Configures the weight for a registered model."""
        clean_name = name.strip().lower()
        self.weights[clean_name] = float(weight)
        logger.info(f"Set ensemble weight for '{clean_name}' to {weight:.4f}")
        
    def get_normalized_weights(self) -> Dict[str, float]:
        """
        Normalizes weights of registered models so they sum to 1.0.
        Models configured in settings but not registered are excluded from normalization.
        """
        active_weights = {
            name: self.weights.get(name, 0.0) 
            for name in self.models.keys()
        }
        total = sum(active_weights.values())
        if total == 0:
            if not active_weights:
                return {}
            # Fallback to equal weights if all active weights are zero
            equal_val = 1.0 / len(active_weights)
            return {k: equal_val for k in active_weights}
        return {k: v / total for k, v in active_weights.items()}
        
    def predict_proba(self, X: pd.DataFrame) -> np.ndarray:
        """
        Computes the weighted ensemble probability of price increasing (class 1).
        
        Args:
            X: Features dataframe
            
        Returns:
            np.ndarray: Unified ensemble probabilities for each sample
        """
        if not self.models:
            raise ValueError("WeightedEnsemble: Cannot predict. No models have been registered.")
            
        norm_weights = self.get_normalized_weights()
        ensemble_probs = np.zeros(len(X), dtype=float)
        
        for name, model in self.models.items():
            weight = norm_weights.get(name, 0.0)
            if weight > 0:
                probs = model.predict_proba(X)
                ensemble_probs += probs * weight
                
        return ensemble_probs

    def get_individual_probabilities(self, X: pd.DataFrame) -> Dict[str, np.ndarray]:
        """
        Runs predictions on all active models to return a diagnostic breakdown of probabilities.
        
        Args:
            X: Features dataframe
            
        Returns:
            Dict[str, np.ndarray]: Probabilities generated by each registered model
        """
        breakdown = {}
        for name, model in self.models.items():
            breakdown[name] = model.predict_proba(X)
        return breakdown

    def predict(self, X: pd.DataFrame, threshold: float = 0.5) -> np.ndarray:
        """
        Computes the binary class direction prediction using a probability threshold.
        
        Args:
            X: Features dataframe
            threshold: Probability split boundary
            
        Returns:
            np.ndarray: Binary array (1 or 0) for each sample
        """
        probs = self.predict_proba(X)
        return (probs >= threshold).astype(int)
